### ISSUE TITLE
Similar word not correctly identified

### ISSUE THREAD

**Issue by dotMR** [AshDan20/MyNotebook#1]
Hello @AshDan20 ,

I believe there is an error in the logic to determine word similarity.

I've created the following test which fails currently to illustrate:

```
    @Test
    @DisplayName("Test case to check if edit occurs in the middle of the word")
    void isSimilarInMiddleTest() {
        Assert.isTrue(MNSearchImpl.isSimilarWord("1234567890", "1235567890"));
    }
```

**Comment by AshDan20** [comment]
Hi dotMR, sorry I could check this little late due to office activities. I see, I got the reason that I implemented the logic to just check the last chars of the string. Somehow I mistaken the requirement. I have just tweaked the logic to check similar words and checked in the code. Could you please update at your end once and see. I have added couple of more test cases too. 
Thanks for getting back to me. 
Ashish

**Comment by AshDan20** [comment]
Hi @dotMR , closing the issue.
